version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: agora
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  node:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: agora_node
    restart: always
    environment:
      NODE_ENV: production
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: docker
      DB_PASSWORD: docker
      DB_NAME: agora
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      


volumes:
  postgres_data:
